
-- Inserting 20 more students
INSERT INTO students (id, name, age) VALUES (11, 'Student11', 19);
INSERT INTO students (id, name, age) VALUES (12, 'Student12', 20);
INSERT INTO students (id, name, age) VALUES (13, 'Student13', 21);
INSERT INTO students (id, name, age) VALUES (14, 'Student14', 22);
INSERT INTO students (id, name, age) VALUES (15, 'Student15', 18);
INSERT INTO students (id, name, age) VALUES (16, 'Student16', 19);
INSERT INTO students (id, name, age) VALUES (17, 'Student17', 20);
INSERT INTO students (id, name, age) VALUES (18, 'Student18', 21);
INSERT INTO students (id, name, age) VALUES (19, 'Student19', 22);
INSERT INTO students (id, name, age) VALUES (20, 'Student20', 18);
INSERT INTO students (id, name, age) VALUES (21, 'Student21', 19);
INSERT INTO students (id, name, age) VALUES (22, 'Student22', 20);
INSERT INTO students (id, name, age) VALUES (23, 'Student23', 21);
INSERT INTO students (id, name, age) VALUES (24, 'Student24', 22);
INSERT INTO students (id, name, age) VALUES (25, 'Student25', 18);
INSERT INTO students (id, name, age) VALUES (26, 'Student26', 19);
INSERT INTO students (id, name, age) VALUES (27, 'Student27', 20);
INSERT INTO students (id, name, age) VALUES (28, 'Student28', 21);
INSERT INTO students (id, name, age) VALUES (29, 'Student29', 22);
INSERT INTO students (id, name, age) VALUES (30, 'Student30', 18);

-- Enrolling new students in courses
INSERT INTO student_courses (student_id, course_id) VALUES (11, 9);
INSERT INTO student_courses (student_id, course_id) VALUES (11, 8);
INSERT INTO student_courses (student_id, course_id) VALUES (12, 8);
INSERT INTO student_courses (student_id, course_id) VALUES (12, 10);
INSERT INTO student_courses (student_id, course_id) VALUES (13, 5);
INSERT INTO student_courses (student_id, course_id) VALUES (13, 3);
INSERT INTO student_courses (student_id, course_id) VALUES (14, 5);
INSERT INTO student_courses (student_id, course_id) VALUES (14, 9);
INSERT INTO student_courses (student_id, course_id) VALUES (15, 7);
INSERT INTO student_courses (student_id, course_id) VALUES (15, 6);
INSERT INTO student_courses (student_id, course_id) VALUES (16, 2);
INSERT INTO student_courses (student_id, course_id) VALUES (16, 9);
INSERT INTO student_courses (student_id, course_id) VALUES (17, 5);
INSERT INTO student_courses (student_id, course_id) VALUES (17, 2);
INSERT INTO student_courses (student_id, course_id) VALUES (18, 9);
INSERT INTO student_courses (student_id, course_id) VALUES (18, 6);
INSERT INTO student_courses (student_id, course_id) VALUES (19, 8);
INSERT INTO student_courses (student_id, course_id) VALUES (19, 4);
INSERT INTO student_courses (student_id, course_id) VALUES (20, 8);
INSERT INTO student_courses (student_id, course_id) VALUES (20, 3);
INSERT INTO student_courses (student_id, course_id) VALUES (21, 7);
INSERT INTO student_courses (student_id, course_id) VALUES (21, 9);
INSERT INTO student_courses (student_id, course_id) VALUES (22, 1);
INSERT INTO student_courses (student_id, course_id) VALUES (22, 9);
INSERT INTO student_courses (student_id, course_id) VALUES (23, 5);
INSERT INTO student_courses (student_id, course_id) VALUES (23, 3);
INSERT INTO student_courses (student_id, course_id) VALUES (24, 1);
INSERT INTO student_courses (student_id, course_id) VALUES (24, 7);
INSERT INTO student_courses (student_id, course_id) VALUES (25, 10);
INSERT INTO student_courses (student_id, course_id) VALUES (25, 7);
INSERT INTO student_courses (student_id, course_id) VALUES (26, 2);
INSERT INTO student_courses (student_id, course_id) VALUES (26, 6);
INSERT INTO student_courses (student_id, course_id) VALUES (27, 2);
INSERT INTO student_courses (student_id, course_id) VALUES (27, 7);
INSERT INTO student_courses (student_id, course_id) VALUES (28, 10);
INSERT INTO student_courses (student_id, course_id) VALUES (28, 6);
INSERT INTO student_courses (student_id, course_id) VALUES (29, 6);
INSERT INTO student_courses (student_id, course_id) VALUES (29, 10);
INSERT INTO student_courses (student_id, course_id) VALUES (30, 4);
INSERT INTO student_courses (student_id, course_id) VALUES (30, 10);